<?php

return [
    'allowed_extensions' => ['pdf', 'doc', 'docx'],
    'status_steps' => [
        'Uploaded' => 20,
        'Parsing' => 45,
        'Analyzing' => 80,
        'Completed' => 100,
        'Failed' => 0,
    ],
    'scoring' => [
        'contact_details' => 10,
        'education' => 15,
        'skills' => 25,
        'experience' => 20,
        'projects' => 10,
        'formatting' => 10,
        'job_role_match' => 10,
    ],
    'section_keywords' => [
        'education' => ['education', 'academic', 'academics', 'qualification', 'qualifications'],
        'experience' => ['experience', 'work experience', 'employment', 'internship', 'internships'],
        'projects' => ['projects', 'project', 'academic projects', 'personal projects'],
        'skills' => ['skills', 'technical skills', 'key skills', 'technologies', 'tech stack'],
        'summary' => ['summary', 'profile', 'career objective', 'objective'],
    ],
    'education_keywords' => [
        'b.tech',
        'b.e',
        'b.sc',
        'm.tech',
        'mca',
        'bca',
        'degree',
        'university',
        'college',
        'cgpa',
        'gpa',
        'graduation',
    ],
    'experience_keywords' => [
        'experience',
        'internship',
        'intern',
        'developer',
        'engineer',
        'worked',
        'company',
        'organization',
        'freelance',
    ],
    'project_keywords' => [
        'project',
        'application',
        'system',
        'website',
        'portal',
        'dashboard',
        'module',
        'api',
        'github',
    ],
];
